/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAppComplexityReferenceRouteImport } from './routes/_auth/app/complexity-reference'
import { Route as AuthAppPatternCheatsheetRouteImport } from './routes/_auth/app/pattern-cheatsheet'
import { Route as AuthAppPythonReferenceRouteImport } from './routes/_auth/app/python-reference'
import { Route as AuthAppStudyPlanRouteImport } from './routes/_auth/app/study-plan'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppTopicsTopicSlugIndexRouteImport } from './routes/_auth/app/topics/$topicSlug/index'
import { Route as AuthAppTopicsTopicSlugSubtopicSlugRouteImport } from './routes/_auth/app/topics/$topicSlug/$subtopicSlug'
import { Route as AuthAppTopicsTopicSlugMixedPracticeRouteImport } from './routes/_auth/app/topics/$topicSlug/mixed-practice'
import { Route as AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRouteImport } from './routes/_auth/app/topics/$topicSlug/$subtopicSlug.$questionSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppComplexityReferenceRoute =
  AuthAppComplexityReferenceRouteImport.update({
    id: '/complexity-reference',
    path: '/complexity-reference',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPatternCheatsheetRoute =
  AuthAppPatternCheatsheetRouteImport.update({
    id: '/pattern-cheatsheet',
    path: '/pattern-cheatsheet',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPythonReferenceRoute = AuthAppPythonReferenceRouteImport.update({
  id: '/python-reference',
  path: '/python-reference',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppStudyPlanRoute = AuthAppStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppTopicsTopicSlugIndexRoute =
  AuthAppTopicsTopicSlugIndexRouteImport.update({
    id: '/topics/$topicSlug/',
    path: '/topics/$topicSlug/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppTopicsTopicSlugSubtopicSlugRoute =
  AuthAppTopicsTopicSlugSubtopicSlugRouteImport.update({
    id: '/topics/$topicSlug/$subtopicSlug',
    path: '/topics/$topicSlug/$subtopicSlug',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppTopicsTopicSlugMixedPracticeRoute =
  AuthAppTopicsTopicSlugMixedPracticeRouteImport.update({
    id: '/topics/$topicSlug/mixed-practice',
    path: '/topics/$topicSlug/mixed-practice',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRoute =
  AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRouteImport.update({
    id: '/$questionSlug',
    path: '/$questionSlug',
    getParentRoute: () => AuthAppTopicsTopicSlugSubtopicSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/app/complexity-reference': typeof AuthAppComplexityReferenceRoute
  '/app/pattern-cheatsheet': typeof AuthAppPatternCheatsheetRoute
  '/app/python-reference': typeof AuthAppPythonReferenceRoute
  '/app/study-plan': typeof AuthAppStudyPlanRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/topics/$topicSlug/$subtopicSlug': typeof AuthAppTopicsTopicSlugSubtopicSlugRouteWithChildren
  '/app/topics/$topicSlug/mixed-practice': typeof AuthAppTopicsTopicSlugMixedPracticeRoute
  '/app/topics/$topicSlug/': typeof AuthAppTopicsTopicSlugIndexRoute
  '/app/topics/$topicSlug/$subtopicSlug/$questionSlug': typeof AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/app/complexity-reference': typeof AuthAppComplexityReferenceRoute
  '/app/pattern-cheatsheet': typeof AuthAppPatternCheatsheetRoute
  '/app/python-reference': typeof AuthAppPythonReferenceRoute
  '/app/study-plan': typeof AuthAppStudyPlanRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/topics/$topicSlug/$subtopicSlug': typeof AuthAppTopicsTopicSlugSubtopicSlugRouteWithChildren
  '/app/topics/$topicSlug/mixed-practice': typeof AuthAppTopicsTopicSlugMixedPracticeRoute
  '/app/topics/$topicSlug': typeof AuthAppTopicsTopicSlugIndexRoute
  '/app/topics/$topicSlug/$subtopicSlug/$questionSlug': typeof AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/app/complexity-reference': typeof AuthAppComplexityReferenceRoute
  '/_auth/app/pattern-cheatsheet': typeof AuthAppPatternCheatsheetRoute
  '/_auth/app/python-reference': typeof AuthAppPythonReferenceRoute
  '/_auth/app/study-plan': typeof AuthAppStudyPlanRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/topics/$topicSlug/$subtopicSlug': typeof AuthAppTopicsTopicSlugSubtopicSlugRouteWithChildren
  '/_auth/app/topics/$topicSlug/mixed-practice': typeof AuthAppTopicsTopicSlugMixedPracticeRoute
  '/_auth/app/topics/$topicSlug/': typeof AuthAppTopicsTopicSlugIndexRoute
  '/_auth/app/topics/$topicSlug/$subtopicSlug/$questionSlug': typeof AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/complexity-reference'
    | '/app/pattern-cheatsheet'
    | '/app/python-reference'
    | '/app/study-plan'
    | '/api/auth/$'
    | '/app/'
    | '/app/topics/$topicSlug/$subtopicSlug'
    | '/app/topics/$topicSlug/mixed-practice'
    | '/app/topics/$topicSlug/'
    | '/app/topics/$topicSlug/$subtopicSlug/$questionSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/complexity-reference'
    | '/app/pattern-cheatsheet'
    | '/app/python-reference'
    | '/app/study-plan'
    | '/api/auth/$'
    | '/app'
    | '/app/topics/$topicSlug/$subtopicSlug'
    | '/app/topics/$topicSlug/mixed-practice'
    | '/app/topics/$topicSlug'
    | '/app/topics/$topicSlug/$subtopicSlug/$questionSlug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_auth/app/complexity-reference'
    | '/_auth/app/pattern-cheatsheet'
    | '/_auth/app/python-reference'
    | '/_auth/app/study-plan'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/topics/$topicSlug/$subtopicSlug'
    | '/_auth/app/topics/$topicSlug/mixed-practice'
    | '/_auth/app/topics/$topicSlug/'
    | '/_auth/app/topics/$topicSlug/$subtopicSlug/$questionSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/complexity-reference': {
      id: '/_auth/app/complexity-reference'
      path: '/complexity-reference'
      fullPath: '/app/complexity-reference'
      preLoaderRoute: typeof AuthAppComplexityReferenceRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/pattern-cheatsheet': {
      id: '/_auth/app/pattern-cheatsheet'
      path: '/pattern-cheatsheet'
      fullPath: '/app/pattern-cheatsheet'
      preLoaderRoute: typeof AuthAppPatternCheatsheetRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/python-reference': {
      id: '/_auth/app/python-reference'
      path: '/python-reference'
      fullPath: '/app/python-reference'
      preLoaderRoute: typeof AuthAppPythonReferenceRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/study-plan': {
      id: '/_auth/app/study-plan'
      path: '/study-plan'
      fullPath: '/app/study-plan'
      preLoaderRoute: typeof AuthAppStudyPlanRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/topics/$topicSlug/': {
      id: '/_auth/app/topics/$topicSlug/'
      path: '/topics/$topicSlug'
      fullPath: '/app/topics/$topicSlug/'
      preLoaderRoute: typeof AuthAppTopicsTopicSlugIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/topics/$topicSlug/$subtopicSlug': {
      id: '/_auth/app/topics/$topicSlug/$subtopicSlug'
      path: '/topics/$topicSlug/$subtopicSlug'
      fullPath: '/app/topics/$topicSlug/$subtopicSlug'
      preLoaderRoute: typeof AuthAppTopicsTopicSlugSubtopicSlugRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/topics/$topicSlug/mixed-practice': {
      id: '/_auth/app/topics/$topicSlug/mixed-practice'
      path: '/topics/$topicSlug/mixed-practice'
      fullPath: '/app/topics/$topicSlug/mixed-practice'
      preLoaderRoute: typeof AuthAppTopicsTopicSlugMixedPracticeRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/topics/$topicSlug/$subtopicSlug/$questionSlug': {
      id: '/_auth/app/topics/$topicSlug/$subtopicSlug/$questionSlug'
      path: '/$questionSlug'
      fullPath: '/app/topics/$topicSlug/$subtopicSlug/$questionSlug'
      preLoaderRoute: typeof AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRouteImport
      parentRoute: typeof AuthAppTopicsTopicSlugSubtopicSlugRoute
    }
  }
}

interface AuthAppTopicsTopicSlugSubtopicSlugRouteChildren {
  AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRoute: typeof AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRoute
}

const AuthAppTopicsTopicSlugSubtopicSlugRouteChildren: AuthAppTopicsTopicSlugSubtopicSlugRouteChildren =
  {
    AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRoute:
      AuthAppTopicsTopicSlugSubtopicSlugQuestionSlugRoute,
  }

const AuthAppTopicsTopicSlugSubtopicSlugRouteWithChildren =
  AuthAppTopicsTopicSlugSubtopicSlugRoute._addFileChildren(
    AuthAppTopicsTopicSlugSubtopicSlugRouteChildren,
  )

interface AuthAppRouteRouteChildren {
  AuthAppComplexityReferenceRoute: typeof AuthAppComplexityReferenceRoute
  AuthAppPatternCheatsheetRoute: typeof AuthAppPatternCheatsheetRoute
  AuthAppPythonReferenceRoute: typeof AuthAppPythonReferenceRoute
  AuthAppStudyPlanRoute: typeof AuthAppStudyPlanRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppTopicsTopicSlugSubtopicSlugRoute: typeof AuthAppTopicsTopicSlugSubtopicSlugRouteWithChildren
  AuthAppTopicsTopicSlugMixedPracticeRoute: typeof AuthAppTopicsTopicSlugMixedPracticeRoute
  AuthAppTopicsTopicSlugIndexRoute: typeof AuthAppTopicsTopicSlugIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppComplexityReferenceRoute: AuthAppComplexityReferenceRoute,
  AuthAppPatternCheatsheetRoute: AuthAppPatternCheatsheetRoute,
  AuthAppPythonReferenceRoute: AuthAppPythonReferenceRoute,
  AuthAppStudyPlanRoute: AuthAppStudyPlanRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppTopicsTopicSlugSubtopicSlugRoute:
    AuthAppTopicsTopicSlugSubtopicSlugRouteWithChildren,
  AuthAppTopicsTopicSlugMixedPracticeRoute:
    AuthAppTopicsTopicSlugMixedPracticeRoute,
  AuthAppTopicsTopicSlugIndexRoute: AuthAppTopicsTopicSlugIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
